Add voter counter
Sut103/7DaysPoll-for-Discord pull request #23
Opened 2024-04-07 09:03 UTC by shokkunrf

https://github.com/Sut103/7DaysPoll-for-Discord/issues/4#issuecomment-1936924525

2024-04-09 04:15 UTC, Sut103 commented
良い機能

あくまで1日でも候補日がある人のカウントということで良い?
想定される全員が投票したことを確認する機能であれば、
1日も候補日がなかった人を明示的に「確認したが無投票」とういう状態にできても良いのかなと思った。

2024-04-10 14:47 UTC, shokkunrf commented
たしかに〜ってことで❌を追加しました

2024-04-16 03:49 UTC, Sut103 requested changes

2024-04-16 03:49 UTC, Sut103 commented on app/command/poll.go
> +	content += fmt.Sprintf("%s %s\n", emojis[7], "Absence")
weekdaysに合わせて言語対応したい。
構造体Choices等にweekdaysとabsenceを定義して、汎用化した`GetWeekdays()`中で言語選択する？

2024-04-16 13:48 UTC, shokkunrf commented on app/command/poll.go
> +	content += fmt.Sprintf("%s %s\n", emojis[7], "Absence")
構造体Choiceを追加した 
https://github.com/Sut103/7DaysPoll-for-Discord/pull/23/commits/cd3b5a741a09f2273728200a16d57253167309bf

2024-04-16 13:49 UTC, shokkunrf commented on app/command/poll.go
> +	content += fmt.Sprintf("%s %s\n", emojis[7], "Absence")
もしかしてこういうのを想定してた？
```go
  [discordgo.Locale]Choices{
    weekdays: []stiring
    absence: string
  }
```

2024-04-20 03:16 UTC, Sut103 approved these changes

2024-04-20 03:18 UTC, merged