add: specified date poll
Sut103/7DaysPoll-for-Discord pull request #8
Opened 2024-02-12 13:28 UTC by Sut103

2024-02-13 11:29 UTC, shokkunrf requested changes

2024-02-13 11:29 UTC, shokkunrf commented on manage/register.go
> +				Description: "If you have a desired date to start the poll. for example, 20240212",
`for example, 20240212` Discordで表示する日付の形式がMM/DDだからこれに合わせたい

2024-02-13 11:44 UTC, Sut103 commented on manage/register.go
> +				Name:        "start-date",
`desired date` は`start-date`の説明なので、ちょっと統一し難い気もする。
`specified date`は`desired date`にしたほうが一貫性がありそうだ。

2024-02-13 12:21 UTC, Sut103 commented on manage/register.go
> +				Description: "If you have a desired date to start the poll. for example, 20240212",
「これに合わせる」 というのは
* スラッシュ込みのフォーマットにしたい(YYYY/MM/DD)
* 月日のみの指定にしたい(MMDD)

だとどっち？

2024-02-13 12:26 UTC, shokkunrf commented on manage/register.go
> +				Description: "If you have a desired date to start the poll. for example, 20240212",
スラッシュ込みかつ月日のみにしたい(MM/DD)
ダメそうなら、月日のみの指定にしたい(MMDD)

2024-02-13 12:35 UTC, Sut103 commented on manage/register.go
> +				Description: "If you have a desired date to start the poll. for example, 20240212",
理解した。

曜日を出している以上、年が必須なのではと思うけどいかが。
直近一年間の未来日での利用に制限するなら確かに月日でも良い。ただ、その旨明記するようにしたいかな。

2024-02-13 12:38 UTC, shokkunrf commented on manage/register.go
> +				Name:        "start-date",
たしかに

2024-02-16 11:24 UTC, shokkunrf commented on manage/register.go
> +				Description: "If you have a desired date to start the poll. for example, 20240212",
1年以上先の7日間の予定を聞きたい場合ってないんじゃないかな。

> 直近一年間の未来日での利用に制限する

でいいと思う。コマンドの説明に書いてもいいしBotの説明に書いても良さそう

2024-02-17 09:11 UTC, Sut103 commented on manage/register.go
> +				Description: "If you have a desired date to start the poll. for example, 20240212",
考え直した。

MM/DDしか入力できないのであれば少なくとも前後一年間であることは自明。
過去日を必要とするユースケースもかなり特殊なものなので考慮する必要なし。

ということでMM/DDにします。

2024-02-17 09:35 UTC, Sut103 commented on manage/register.go
> +				Name:        "start-date",
コマンド説明: `If you have desired options, please specify the initial date. Example: MM/DD`
オプション説明: Starting 7DaysPoll from initial date(Today or Specify date).
とします。

2024-02-17 12:18 UTC, shokkunrf approved these changes
:+1:

2024-02-17 12:19 UTC, merged